language: python
sudo: required
dist: trusty
python:
    - "2.7"
env:
    - CKANVERSION=master PGVERSION=9.3
services:
    - redis-server
install:
    - bash bin/travis-build.bash
    - pip install coveralls -U
script: sh bin/travis-run.sh
after_success:
    - coveralls
cache:
  directories:
    - $HOME/.cache/pip
